J_SAL = "JOIN Salary s ON e.Employee_ID = s.Employee_ID"
J_DEP = "JOIN Department d ON e.Department_ID = d.Department_ID"
J_PER = "JOIN Performance p ON e.Employee_ID = p.Employee_ID"

QUERIES = [
    ("Display all departments", "SELECT * FROM Department"),
    ("Display all employees", "SELECT * FROM Employee"),
    ("Display all salary records", "SELECT * FROM Salary"),
    ("Display all performance records", "SELECT * FROM Performance"),
    ("Employees of the IT department", f"SELECT e.Employee_ID, e.Name, e.Designation FROM Employee e {J_DEP} WHERE d.Department_Name = 'IT'"),
    ("Employees with more than 10 years of experience", "SELECT Employee_ID, Name, Experience_Years FROM Employee WHERE Experience_Years > 10"),
    ("Employees sorted by name", "SELECT Employee_ID, Name, Age FROM Employee ORDER BY Name"),
    ("Top 10 total salaries", "SELECT Employee_ID, Basic_Salary, Bonus, Total_Salary FROM Salary ORDER BY Total_Salary DESC LIMIT 10"),
    ("Employees with a performance score of 4 or more", "SELECT Employee_ID, Performance_Score FROM Performance WHERE Performance_Score >= 4"),
    ("Employees with their department", f"SELECT e.Name, d.Department_Name FROM Employee e {J_DEP}"),
    ("Employees with salary details", f"SELECT e.Name, s.Basic_Salary, s.Bonus, s.Total_Salary FROM Employee e {J_SAL}"),
    ("Employees with performance scores", f"SELECT e.Name, p.Performance_Score FROM Employee e {J_PER}"),
    ("Complete employee profile (4-table join)", f"SELECT e.Employee_ID, e.Name, d.Department_Name, e.Designation, s.Total_Salary, p.Performance_Score FROM Employee e {J_DEP} {J_SAL} {J_PER}"),
    ("Employees per department", f"SELECT d.Department_Name, COUNT(*) AS Employees FROM Employee e {J_DEP} GROUP BY d.Department_Name"),
    ("Average salary per department", f"SELECT d.Department_Name, ROUND(AVG(s.Basic_Salary), 0) AS Avg_Salary FROM Employee e {J_DEP} {J_SAL} GROUP BY d.Department_Name ORDER BY Avg_Salary DESC"),
    ("Average performance per department", f"SELECT d.Department_Name, ROUND(AVG(p.Performance_Score), 2) AS Avg_Score FROM Employee e {J_DEP} {J_PER} GROUP BY d.Department_Name ORDER BY Avg_Score DESC"),
    ("Maximum basic salary", "SELECT MAX(Basic_Salary) AS Max_Salary FROM Salary"),
    ("Minimum basic salary", "SELECT MIN(Basic_Salary) AS Min_Salary FROM Salary"),
    ("Average total salary", "SELECT ROUND(AVG(Total_Salary), 2) AS Avg_Total_Salary FROM Salary"),
    ("Total bonus per department", f"SELECT d.Department_Name, SUM(s.Bonus) AS Total_Bonus FROM Employee e {J_DEP} {J_SAL} GROUP BY d.Department_Name"),
    ("Highest-paid employee in each department", f"SELECT d.Department_Name, e.Name, s.Basic_Salary FROM Employee e {J_DEP} {J_SAL} WHERE s.Basic_Salary = (SELECT MAX(s2.Basic_Salary) FROM Salary s2 JOIN Employee e2 ON s2.Employee_ID = e2.Employee_ID WHERE e2.Department_ID = e.Department_ID)"),
    ("Employees earning above the average salary", f"SELECT e.Name, s.Basic_Salary FROM Employee e {J_SAL} WHERE s.Basic_Salary > (SELECT AVG(Basic_Salary) FROM Salary) ORDER BY s.Basic_Salary DESC"),
    ("High performers paid below average", f"SELECT e.Name, p.Performance_Score, s.Basic_Salary FROM Employee e {J_SAL} {J_PER} WHERE p.Performance_Score >= 4 AND s.Basic_Salary < (SELECT AVG(Basic_Salary) FROM Salary)"),
    ("Departments with more than 15 employees", "SELECT Department_ID, COUNT(*) AS Employees FROM Employee GROUP BY Department_ID HAVING COUNT(*) > 15"),
    ("Employees whose name starts with Employee_01", "SELECT * FROM Employee WHERE Name LIKE 'Employee_01%'"),
    ("Search designation by keyword", "SELECT Employee_ID, Name, Designation FROM Employee WHERE UPPER(Designation) LIKE '%ANALYST%'"),
    ("Gender-wise employees and average salary", f"SELECT e.Gender, COUNT(*) AS Employees, ROUND(AVG(s.Basic_Salary), 0) AS Avg_Salary FROM Employee e {J_SAL} GROUP BY e.Gender"),
    ("Average salary by designation", f"SELECT e.Designation, ROUND(AVG(s.Basic_Salary), 0) AS Avg_Salary FROM Employee e {J_SAL} GROUP BY e.Designation ORDER BY Avg_Salary DESC"),
    ("Salary by experience band", f"SELECT CASE WHEN e.Experience_Years <= 2 THEN '0-2 years' WHEN e.Experience_Years <= 5 THEN '3-5 years' WHEN e.Experience_Years <= 10 THEN '6-10 years' ELSE '10+ years' END AS Experience_Band, COUNT(*) AS Employees, ROUND(AVG(s.Basic_Salary), 0) AS Avg_Salary FROM Employee e {J_SAL} GROUP BY Experience_Band ORDER BY MIN(e.Experience_Years)"),
    ("Employees with a bonus above 5000", "SELECT Employee_ID, Bonus FROM Salary WHERE Bonus > 5000"),
    ("Employees joined per year", "SELECT Joining_Year, COUNT(*) AS Employees FROM Employee GROUP BY Joining_Year ORDER BY Joining_Year"),
    ("Top 5 performers with salary", f"SELECT e.Name, p.Performance_Score, s.Total_Salary FROM Employee e {J_SAL} {J_PER} ORDER BY p.Performance_Score DESC, s.Total_Salary DESC LIMIT 5"),
    ("Average salary by performance score", f"SELECT p.Performance_Score, COUNT(*) AS Employees, ROUND(AVG(s.Basic_Salary), 0) AS Avg_Salary FROM Employee e {J_SAL} {J_PER} GROUP BY p.Performance_Score ORDER BY p.Performance_Score"),
    ("Employees with a missing age", "SELECT * FROM Employee WHERE Age IS NULL"),
]
